"""Markdown rendering of research reports for the notebook."""
# AI-ASSISTED: Claude (claude-opus-5-5), Prompt: 'Render ResearchReport/FinalReport as Markdown',
# Date: 2026-10-07

from __future__ import annotations

from .schemas import FinalReport, ResearchReport


def report_markdown(r: ResearchReport) -> str:
    lines = [f"## Research report — {r.ticker}", "### 1. Financial Health Summary", r.financial_health_summary,
             "", f"**Market sentiment.** {r.market_sentiment_summary}", "", "### 2. Top Three Risks (90 days)"]
    for i, risk in enumerate(r.top_risks, 1):
        lines += [f"**{i}. {risk.title}** — likelihood *{risk.likelihood}*", "", risk.description, ""]
        lines += [f"- {e}" for e in risk.evidence] + [""]
    h = r.hedge_strategy
    lines += ["### 3. Hedge Strategy Recommendation", f"**{h.strategy}** — {h.implementation}", "",
              f"*Data rationale:* {h.data_rationale}", "", f"*Cost / trade-off:* {h.estimated_cost_or_tradeoff}"]
    if isinstance(r, FinalReport):
        lines += ["", "### Critique loop — how Agent A's answer was used", r.clarification_incorporated]
    lines += ["", "*Sources: " + ", ".join(r.data_sources_used) + "*",
              "", "> Educational output generated by an LLM agent system — not investment advice."]
    return "\n".join(lines)
